<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
<!ELEMENT mime-info (mime-type)+>
<!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">
<!ELEMENT mime-type (comment+ , (acronym , expanded-acronym)? , (icon | generic-icon | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
<!ATTLIST mime-type type CDATA #REQUIRED>
<!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
<!ELEMENT comment (#PCDATA)>
<!ATTLIST comment xml:lang CDATA #IMPLIED>
<!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" -->
<!ELEMENT acronym (#PCDATA)>
<!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" -->
<!ELEMENT expanded-acronym (#PCDATA)>
<!ELEMENT icon EMPTY>
<!ATTLIST icon name CDATA #REQUIRED>
<!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification --><!ELEMENT generic-icon EMPTY>
<!ATTLIST generic-icon name (application-x-executable | audio-x-generic | emblem-symbolic-link | folder | font-x-generic | image-x-generic | media-floppy | media-optical | package-x-generic | text-html | text-x-generic | text-x-generic-template | text-x-script | video-x-generic | x-office-address-book | x-office-calendar | x-office-document | x-office-presentation | x-office-spreadsheet) #REQUIRED>
<!ELEMENT glob EMPTY>
<!ATTLIST glob pattern CDATA #REQUIRED>
<!ATTLIST glob weight CDATA "50">
<!ATTLIST glob case-sensitive CDATA #IMPLIED>
<!ELEMENT magic (match)+>
<!ATTLIST magic priority CDATA "50">
<!ELEMENT match (match)*>
<!ATTLIST match offset CDATA #REQUIRED>
<!ATTLIST match type (string | big16 | big32 | little16 | little32 | host16 | host32 | byte) #REQUIRED>
<!ATTLIST match value CDATA #REQUIRED>
<!ATTLIST match mask CDATA #IMPLIED>
<!ELEMENT treemagic (treematch)+>
<!ATTLIST treemagic priority CDATA "50">
<!ELEMENT treematch (treematch)*>
<!ATTLIST treematch path CDATA #REQUIRED>
<!ATTLIST treematch type (file | directory | link) #IMPLIED>
<!ATTLIST treematch match-case (true | false) #IMPLIED>
<!ATTLIST treematch executable (true | false) #IMPLIED>
<!ATTLIST treematch non-empty (true | false) #IMPLIED>
<!ATTLIST treematch mimetype CDATA #IMPLIED>
<!ELEMENT root-XML EMPTY>
<!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
<!ATTLIST root-XML localName CDATA #REQUIRED>
<!ELEMENT alias EMPTY>
<!ATTLIST alias type CDATA #REQUIRED>
<!ELEMENT sub-class-of EMPTY>
<!ATTLIST sub-class-of type CDATA #REQUIRED>
]>
<!--
The freedesktop.org shared MIME database (this file) was created by merging
several existing MIME databases (all released under the GNU GPL).

It comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law. You may
redistribute copies of freedesktop.org.xml under the terms of the GNU General
Public License version 2 or later. For more information about these matters,
see the file named COPYING.

The latest version is available from:

	http://www.freedesktop.org/wiki/Software/shared-mime-info/

To extend this database, users and applications should create additional
XML files in the 'packages' directory and run the update-mime-database
command to generate the output files.
-->



<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">

  <mime-type type="audio/x-mod">
    <comment>Amiga SoundTracker audio</comment>
    <comment xml:lang="sv">Amiga SoundTracker-ljud</comment>
    <glob pattern="*.mod"/>
    <glob pattern="*.ult"/>
    <glob pattern="*.uni"/>
    <glob pattern="*.m15"/>
    <glob pattern="*.mtm"/>
    <glob pattern="*.669"/>
    <glob pattern="*.med"/>
  </mime-type>
  
  <mime-type type="text/x-rst">
    <comment>ReStructuredText document</comment>
    <comment xml:lang="sv">ReStructuredText-dokument</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-rst"/>
    <glob pattern="*.rst"/>
  </mime-type>
  
</mime-info>


